name: Pull Request CI

on:
  pull_request:
    branches: 
      - main
      - develop

jobs:
  pr_tests:
    permissions: write-all
    name: PR E2E Tests
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=rootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout the test repository
        uses: actions/checkout@v4
  

      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      
      - name: Install MySQL Client & Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          python -m pip install --upgrade pip
          pip install mysql-connector-python

      - name: Wait for MySQL and Initialize Database
        run: python init_db.py
      
      - name: Create reports folder
        run: |
          mkdir -p reports/coverage
          mkdir -p reports/robotmetrics

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          npm install @playwright/test
          npx playwright install-deps
          rfbrowser init

      - name: Run the tests
        env:
          # For real testing environments these variables must be secret and not exposed.
          DB_NAME: testdb
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_HOST: localhost
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: pabot --processes 4 -d ./reports --output output.xml -v HEADLESS:true -v PIPELINE:true --nostatusrc  --testlevelsplit ./tests

      - name: Validate Test Coverage
        if: always()
        id: test_coverage
        run: |
          python ./resources/libraries/test_coverage_validator.py \
            ./reports/output.xml \
            --min-coverage 80 \
            --output-dir ./reports/coverage || exit 1

      - name: Read Markdown Report
        id: read_report
        if: always()
        run: |
          report_file=$(ls ./reports/coverage/test_coverage_report_*.md | head -n 1)
          echo "report_path=$report_file" >> $GITHUB_OUTPUT
          cat $report_file

      - name: Create GitHub Comment
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const reportPath = '${{ steps.read_report.outputs.report_path }}';
            const reportContent = fs.readFileSync(reportPath, 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: reportContent
            });

      - name: Upload PR Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-test-results
          path: |
            ./reports
            ./reports/coverage
            ./reports/robotmetrics
          retention-days: 5
          if-no-files-found: ignore
